version: "3"

services:

  app:
    image: sravya98/projectscm
    ports:
      - 80:8102
  #   volumes:
  #     - ./:/app
     
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - 2181:2181
    # volumes:
    #   - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - 9092:9092
    # volumes:
    #   - kafka_data:/bitnami
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_HEAP_OPTS=-Xmx500M
    depends_on:
      - zookeeper
    # healthcheck:
    #   test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
    #   interval: 15s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

  sockets:
    image: sokser:latest
    ports:
      - 12345:12345
    # volumes:
    #   - ./server:/main1/server
  producer:
       
    image: prodk:latest
    depends_on:
      - kafka
      # kafka:
      #   condition: service_healthy 
    # volumes:
    #   - ./producer:/main1/producer
  consumer:
   
    image: consk:latest

    depends_on:
      - kafka
      # kafka:
      #   condition: service_healthy
    # volumes:
    #   - ./consumer:/main1/consumer

# volumes:
#   zookeeper_data:
#     driver: local
#   kafka_data:
#     driver: local